#!/usr/bin/env python3

"""This is the main script for PDE problems in one space dimension.

For setting up parameters use the file `defauls.py` or options via command prompt.
More information are available with "cls1 --help".

"""

from parser import ArgumentParserFEM1D

import command as cmd
import profiler


@profiler.profile
def main():
    parser = ArgumentParserFEM1D()
    args = parser.parse_args()

    if args.args:
        print(args)

    if hasattr(args, "profile"):
        profiler.PRINT_PROFILE = args.profile

    if args.program == "test":
        command = cmd.TestCommand(args)
    elif args.program == "help":
        command = cmd.HelpCommand(args)
    elif hasattr(args, "plot") and args.plot:
        command = cmd.PlotCommand(args)
    elif hasattr(args, "animate") and args.animate:
        command = cmd.AnimateCommand(args)
    elif hasattr(args, "eoc") and args.eoc:
        command = cmd.EOCCommand(args)
    elif hasattr(args, "calculation") and args.calculation:
        command = cmd.CalculationCommand(args)
    else:
        raise ValueError("no action specified")

    command.execute()


if __name__ == "__main__":
    main()
