#!/usr/bin/env python3

"""This is the main script for Conservation law problems in one space dimension.

For setting up parameters use the file `defauls.py` or options via command prompt.
More information are available with "cls1 --help".

"""

from parser import CustomArgumentParser

import command as cmd
import profiler


@profiler.profile
def main():
    parser = CustomArgumentParser()
    args = parser.parse_arguments()

    if args.args:
        print(args)

    if hasattr(args, "profile"):
        profiler.PRINT_PROFILE = args.profile

    if args.command == "test":
        command = cmd.TestCommand(args)
    elif args.command == "help":
        command = cmd.HelpCommand(args)
    elif hasattr(args, "plot") and args.plot:
        command = cmd.PlotCommand(args)
    elif hasattr(args, "animate") and args.animate:
        command = cmd.AnimateCommand(args)
    elif hasattr(args, "eoc") and args.eoc:
        command = cmd.EOCCommand(args)
    elif hasattr(args, "calculate") and args.calculation:
        command = cmd.CalculationCommand(args)
    elif args.command == "generate-data":
        command = cmd.GenerateData(args)
    elif args.command == "train-network":
        command = cmd.TrainNetwork(args)
    else:
        raise ValueError("No Action specified.")

    command.execute()


if __name__ == "__main__":
    main()
