#!/usr/bin/env sh

source_dir="data/reduced-llf-2/"
mkdir -pv $source_dir

echo
echo "######################################################################"
echo "Generate Second Model"
echo "######################################################################"
echo
echo "---------------------"
echo "Generate Data for the network"
echo "---------------------"
./cls1 generate-data -d $source_dir -s llf +m 2000 -c 40
echo
echo "---------------------"
echo "Train network"
echo "---------------------"
./cls1 train-network llf2 -e 500 --seed 2
./cls1 train-network llf2 -e 2000 --seed 2 --resume -p lr 0.001
